version: '3'
services:
  api:
    image: quay.io/codait/max-image-caption-generator
    # ports: 
      # - "5000:5000"
  kafka-consumer:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python -u main.py
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - api
